### ISSUE TITLE
Consider rewriting in c++

### ISSUE THREAD

**Issue by es3n1n** [User344/ida-rust-plugin-example#1]
Please consider rewriting this project in c++, this will allow you to improve performance and the overall look of the code (it will look better). 

Thanks.

**Comment by imunproductive** [comment]
Your most stared repository out of all your repositories is no-defender. Opinion rejected.
![image](https://github.com/user-attachments/assets/033b2520-3f15-4b0e-baff-9ec952a6a046)

**Comment by es3n1n** [comment]
> Your most stared repository out of all your repositories is no-defender. Opinion rejected.
> ![image](https://github.com/user-attachments/assets/033b2520-3f15-4b0e-baff-9ec952a6a046)

My honest reaction:

![IMG_20241021_041204_489.jpg](https://github.com/user-attachments/assets/284c10c6-2141-4e22-b955-1d064a460e00)
